version: '3.8'

services:
  om1:
    build:
      context: .
      dockerfile: Dockerfile
    image: openmindagi/om1:latest
    container_name: om1
    restart: unless-stopped
    network_mode: host 
    environment:
      - ROS_DOMAIN_ID=0
      - CYCLONEDDS_HOME=/app/cyclonedds/install
      - CYCLONEDDS_URI=file:///cyclonedds/cyclonedds.xml
      - CMAKE_PREFIX_PATH=/app/cyclonedds/install
      - OM_API_KEY=${OM_API_KEY}
    volumes:
      - ./cyclonedds:/cyclonedds
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    command: ["spot"]