name: Copy Docs to Mintlify folder

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  copy-and-replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docs into mintlify
        run: cp -r docs/* mintlify/

      - name: Remove `.mdx` extensions from inside files
        run: |
          find mintlify -type f -exec sed -i 's/\.mdx//g' {} +